### ISSUE TITLE
Смещение нумерации автоинктремента в зависимости от номера задачи

### ISSUE THREAD

**Issue by TheRatG** [octava/BranchingBundle#2]
К сожалению, некоторые идентификаторы привязаны к автоинкременту, что приводит к ошибкам уникальности на внешних сервисах при использовании копий БД.
Для решения этой проблемы используется смещение нумерации в определенных таблицах для каждой ветки.

Пример конфигурации:

```
    alter_increment_map:
        'AppBalanceBundle:Transaction':
            test:
                start: 500000000
                step: 1000
            dev:
                start: 8000000
                step: 1000
        'AppBonusBundle:Bonus':
            test:
                start: 500000000
                step: 1000
            dev:
                start: 8000000
                step: 1000
```
